config/routes.rb
Rails.application.routes.draw do

  resources :example
  get 'analysis/index', to: 'analysis#index'
  get 'analysis/', to: 'analysis#index'
  post 'analysis/analyze', to: 'analysis#analyze'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

end

app/controllers/analysis_controller.rb
require 'nbayes'

class AnalysisController < ApplicationController
  layout "main"

  def analyze
    @issue = params[:text]

    #Creating instances of Naive Bayes classifiers for Referential Emotive, Conative and Phatic functions
    nbayesR = NBayes::Base.new
    nbayesE = NBayes::Base.new
    nbayesC = NBayes::Base.new
    nbayesP = NBayes::Base.new

    #Training

    @CommentsTrain = Comment.all

    @CommentsTrain.each do |comment|
      if comment.referential then labelR= "Yes" else labelR = "No" end
      if comment.emotive then labelE= "Yes" else labelE = "No" end
      if comment.conative then labelC= "Yes" else labelC = "No" end
      if comment.phatic then labelP= "Yes" else labelP = "No" end


      tokens= tokenize(comment.comment)
      nbayesR.train(tokens, labelR)
      nbayesE.train(tokens, labelE)
      nbayesC.train(tokens, labelC)
      nbayesP.train(tokens, labelP)
    end

    #Classification
    issueTokenized = tokenize(@issue)
    @resultR = nbayesR.classify(issueTokenized).max_class
    @resultC = nbayesC.classify(issueTokenized).max_class
    @resultE = nbayesE.classify(issueTokenized).max_class
    @resultP = nbayesP.classify(issueTokenized).max_class



  end


  def tokenize(stringToSplit)
    tokens = stringToSplit.split + wngrams(2,stringToSplit) + wngrams(3,stringToSplit) + chngrams(2,stringToSplit) + chngrams(3,stringToSplit)
    return tokens
  end
  

  def wngrams(n, text)
    iMin=0
    iMax=n-1
    tokens = []

    tokenList = text.split
    tokenList.each do
      if(iMin+n <= tokenList.length()) then
        tokens.append((tokenList[iMin..iMax]).join(" "))
        iMin += 1
        iMax += 1
      end
    end
    return  tokens
  end

  def chngrams(n, text)
    iMin=0
    iMax=n-1
    tokens = []
    while iMin+n <= text.length()  do
        tokens.append(text[iMin..iMax])
        iMin += 1
        iMax += 1
    end
    return  tokens
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery unless: -> { request.format.json? }
end

app/controllers/example_controller.rb
class ExampleController < ApplicationController
  layout "main"
  def index

    @CommentsTable = Comment.where('length(comment) < 300 and id_issue>40000 and id_issue<100000')

  end
end

app/helpers/analysis_helper.rb
module AnalysisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/example_helper.rb
module ExampleHelper
end

app/views/analysis/analyze.html.erb
<main>
  <div class="container-fluid">
    <h1 class="mt-4">Analysis</h1>

    <div>
      <%= "Text:  " + @issue  %>



    </div>




      <div class="card mb-4">
        <div class="card-header">
          <i class="fas fa-table mr-1"></i>
          Text functions
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
              <tr>
                <th>Text</th>
                <th>Referential</th>
                <th>Emotive</th>
                <th>Conative</th>
                <th>Phatic</th>

              </tr>
              </thead>

              <tbody>
              <tr>
                <td><%=@issue %></td>
                <td><%=@resultR %></td>
                <td><%=@resultE %></td>
                <td><%=@resultC %></td>
                <td><%=@resultP %></td>
              </tr>
            </table>
          </div>
        </div>
      </div>

      <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active">Analysis</li>
      </ol>

      <div class="row">
        <div class="col-xl-6">
          <div class="card mb-4">
            <div class="card-header">
              <i class="fas fa-chart-area mr-1"></i>
              Comments by communication function
            </div>
            <div class="card-body"><canvas id="myAreaChart" width="100%" height="40"></canvas></div>
          </div>
        </div>
        <div class="col-xl-6">
          <div class="card mb-4">
            <div class="card-header">
              <i class="fas fa-chart-bar mr-1"></i>
              Other graph
            </div>
            <div class="card-body"><canvas id="myBarChart" width="100%" height="40"></canvas></div>
          </div>
        </div>
      </div>
      </div>
      </main>

app/views/analysis/errorPage.html.erb
<p>Error page, contact the administrator! </p>

app/views/analysis/index.html.erb
    <main>
      <div class="container-fluid">
        <h1 class="mt-4">Analyzer of issues and comments</h1>

        <div>
          <%= form_with url: "analyze", method: :post do |form| %>
            <%= form.label :text, "Text (issue/comment):" %>
            <%= form.text_field :text, :required => true %>
            <%= form.submit "Analize" %>
          <% end %>




        </div>



        <div class="card mb-4">
          <div class="card-header">
            <i class="fas fa-table mr-1"></i>
            Instructions
          </div>
          <br>
          <ol>
            <li>
              Type the description of issue or comment
            </li>
            <li>
              Press the "Analyze" button
            </li>
            <li>
              The system will display the analysis, indicating the type of sentences the text contains, example:
            </li>
          </ol>


          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                <tr>
                  <th>Text</th>
                  <th>Referential</th>
                  <th>Emotive</th>
                  <th>Conative</th>
                  <th>Phatic</th>

                </tr>
                </thead>

                <tbody>
                <tr>
                <td>The bug was fixed, Thanks</td>
                  <td>Yes</td>
                  <td>No</td>
                  <td>No</td>
                  <td>Yes</td>
                </tr>
              </table>
            </div>
          </div>
        </div>

      </div>
    </main>

app/views/example/index.html.erb
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
<%= javascript_pack_tag 'application'%>

<main>
  <div class="container-fluid">
    <h1 class="mt-4">Analysis example of communication functions</h1>

    <div class="card mb-4">
      <div class="card-header">
        <i class="fas fa-table mr-1"></i>
        Issues & Comments
      </div>
      <div class="card-body" >
        <div class="table-responsive" >

          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
            <tr>
              <th>#</th>
              <th>Issue Id</th>
              <th>Comment description</th>
              <th>Project</th>
              <th>Referential</th>
              <th>Emotive</th>
              <th>Conative</th>
              <th>Phatic</th>

            </tr>
            </thead>

            <tbody>
            <% @CommentsTable.each do |comment| %>
              <tr>
                <td></td>
                <td><%= comment.id_issue %></td>
                <td><%= comment.comment %></td>
                <td><%= comment.project %></td>
                <td><%= if comment.referential
                          "Yes"
                        else
                          "No"
                        end%></td>
                <td><%= comment.emotive %></td>
                <td><%= comment.conative %></td>
                <td><%= comment.phatic %></td>


              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <ol class="breadcrumb mb-4">
      <li class="breadcrumb-item active">Analysis</li>
    </ol>

    <div class="row">
      <div class="col-xl-6">
        <div class="card mb-4">
          <div class="card-header">
            <i class="fas fa-chart-area mr-1"></i>
            Comments by project
          </div>
          <div class="card-body"><canvas id="myAreaChart" width="100%" height="40"></canvas></div>
          <%= pie_chart @CommentsTable.group(:project).count %>
        </div>
      </div>
      <div class="col-xl-6">
        <div class="card mb-4">
          <div class="card-header">
            <i class="fas fa-chart-bar mr-1"></i>
            Referential comments
          </div>
          <div class="card-body"><canvas id="myBarChart" width="100%" height="40"></canvas></div>
          <%= bar_chart @CommentsTable.group(:referential).count, colors: ["#6f42c1", "#fd7e14"]%>

        </div>
      </div>
      <div class="col-xl-6">
        <div class="card mb-4">
          <div class="card-header">
            <i class="fas fa-chart-bar mr-1"></i>
            Emotive comments
          </div>
          <div class="card-body"><canvas id="myBarChart" width="100%" height="40"></canvas></div>
          <%= bar_chart @CommentsTable.group(:emotive).count,colors: ["#007BFF", "#FFC107"] %>

        </div>
      </div>
      <div class="col-xl-6">
        <div class="card mb-4">
          <div class="card-header">
            <i class="fas fa-chart-bar mr-1"></i>
            Conative comments
          </div>
          <div class="card-body"><canvas id="myBarChart" width="100%" height="40"></canvas></div>
          <%= bar_chart @CommentsTable.group(:conative).count, colors: ["#28a745", "#DC3545"] %>

        </div>
      </div>
      <div class="col-xl-6">
        <div class="card mb-4">
          <div class="card-header">
            <i class="fas fa-chart-bar mr-1"></i>
            Phatic comments
          </div>
          <div class="card-body"><canvas id="myBarChart" width="100%" height="40"></canvas></div>
          <%= bar_chart @CommentsTable.group(:phatic).count, colors: ["#17A2B8", "#e83e8c"] %>

        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CommunicationAnalizer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/main.erb
<%= stylesheet_link_tag "main" %>

<!DOCTYPE html>
<html lang="en">
<head>

    <%= csrf_meta_tags %>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <title>Communication Analyzer</title>
</head>
<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">

  <%= link_to "Home", analysis_index_path, class: "navbar-brand" %>
  <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">

  </form>
  <!-- Navbar-->
  <ul class="navbar-nav ml-auto ml-md-0">
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
        <a class="dropdown-item" href="#">Help</a>
      </div>
    </li>
  </ul>
</nav>

<div id="layoutSidenav">
  <div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
      <div class="sb-sidenav-menu">
        <div class="nav">
          <div class="sb-sidenav-menu-heading">Analysis</div>
          <%= link_to " - Issues", analysis_index_path, class: "nav-link" %>

          <div class="sb-sidenav-menu-heading">Exmples</div>
          <%= link_to " - Communication functions", example_index_path, class: "nav-link" %>
        </div>
      </div>
    </nav>
  </div>


  <div id="layoutSidenav_content">

    <%= yield %>


    <footer class="py-4 bg-light mt-auto">
      <div class="container-fluid">
        <div class="d-flex align-items-center justify-content-between small">
          <div class="text-muted">Copyright &copy; Sandra Ramirez 2021</div>
          <div>
            <a href="#">Privacy Policy</a>

          </div>
        </div>
      </div>
    </footer>
  </div>
</div>

</body>
</html>